### ISSUE TITLE
GitHub CI shows correct output but milestone not added to PR.

### ISSUE THREAD

**Issue by krmanik** [zoispag/action-assign-milestone#73]
I have created a PR for adding milestone. The changes already pushed to upstream but still not adding milestone to other PR.
CI output
```
Run zoispag/action-assign-milestone@v1
Milestone 2.16 release has been assigned to PR #10676
```
But the milestone is not added to the PR.
https://github.com/ankidroid/Anki-Android/pull/10676/files

**Comment by zoispag** [comment]
Hi, thanks for reaching out.

I tested the action on closed PRs, similar to your example.
The action works both for local and forked PRs, with the following workflow:

```yml
name: PR Milestone

on:
  pull_request:
    types: [closed]
  pull_request_target:
    types: [closed]

jobs:
  milestone:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
      - uses: zoispag/action-assign-milestone@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          milestone: "2.16 release" 
```

Please notice the separate `pull_request` and `pull_request_target` events.

See here:
- https://github.com/temp-org-gr/test-milestone-action/pull/7
- https://github.com/temp-org-gr/test-milestone-action/pull/8

Does this help?
